version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # ---------------- KRaft Basics ----------------
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ---------------- Listeners ----------------
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:29092,
        PLAINTEXT_HOST://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:29092,
        PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ---------------- Internal Topics ----------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # ---------------- Storage ----------------
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # ---------------- Cluster ID ----------------
      CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
