apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init-multiple-dbs.sql: |
    CREATE DATABASE hbproductstore;
    CREATE DATABASE hborderstore;
    CREATE DATABASE hbpaymentstore;

    ALTER DATABASE hbproductstore OWNER TO postgres;
    ALTER DATABASE hborderstore OWNER TO postgres;
    ALTER DATABASE hbpaymentstore OWNER TO postgres;
