apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service  
    spec:
        volumes:
         - name: product-data
           emptyDir: {}

        initContainers:
         - name: load-product-data
           image: haseebali5/product-data:latest
           command: ["sh", "-c", "cp /data/products.json /shared/products.json"]
           volumeMounts:
             - name: product-data
               mountPath: /shared
               
        containers:
         - name: product-service
           image: haseebali5/product-service:latest
           env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
           volumeMounts:
            - name: product-data
              mountPath: /app/data
              readOnly: true  