apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-service
  template:
    metadata:
      labels:
        app: ws-service  
    spec:
      containers:
        - name: ws-service
          image: haseebali5/ws-service:latest
          env:
           - name: SPRING_PROFILES_ACTIVE
             value: k8s
          