apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: event-driven-microservices
data:
  server.properties: |
    process.roles=broker,controller
    node.id=0

    listeners=BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    advertised.listeners=BROKER://kafka-0.kafka:9092

    listener.security.protocol.map=BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=BROKER
    controller.listener.names=CONTROLLER

    controller.quorum.voters=0@kafka-0.kafka:9093

    log.dirs=/var/lib/kafka/data
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    auto.create.topics.enable=true
